### PR TITLE
Improve queueing (rewrite)

### LINKED ISSUE #38: Send queue response
We need to send the response here https://github.com/itsapi/github-listener/blob/master/listener.js#L250

### LINKED ISSUE #39: Keep UI in Sync With Queue
Related to #38, we should do the testing before the payload is added to the queue, add the output to an output object which is stored in the queue. Then when it gets to the front of the queue, it is output to the UI.

### LINKED ISSUE #43: UI History
Related to #39. Once we have the queuing working properly, it should be simple to show the queue in the UI: you can scroll down to see previous builds, as well as see waiting builds. This would make it much easier to debug builds...

### PR DESCRIPTION
**Pull request by grit96**
Fixes #38, fixes #43 and fixes #39

### CODE REVIEW

**Comment by grit96** [comment]
Should we address #34 while we are rewriting everything?

**Comment by olls** [comment]
I think it would be simpler to do it afterwards.

**Comment by grit96** [comment]
TODO:

- [ ] Rebuild button in header
- [ ] Update global status in title (need to tell UI the status)
- [ ] Fix failing tests

**Comment by olls** [comment]
Nearly there. Todo:
- [ ] Fix UI when empty
- [ ] Docs for client JS
- [ ] Response from rerun
- [ ] ...

**Comment by olls** [comment]
- [ ] The order seems messed up...

**Comment by grit96** [comment]
I think the order only messes up when lots of builds come in simultaneously. It's the order they get processed and sent to the client.

**Comment by olls** [comment]
Ahh, but maybe we should just order them by id? So they will always be in the same order.

**Pull request merged**
